"""empty message

Revision ID: b0182657b169
Revises: 
Create Date: 2018-04-18 14:06:15.335461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0182657b169'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('dateTime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_date_dateTime'), 'date', ['dateTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_date_dateTime'), table_name='date')
    op.drop_column('date', 'dateTime')
    # ### end Alembic commands ###
